localbin/core/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, FileField, SubmitField, MultipleFileField, HiddenField

"""
Forms for login, registration, create folder and upload file
Some basic validation and message feedback
"""

class CreateFolderForm(FlaskForm):
    folder_name = StringField("Folder name", render_kw={"placeholder": "输入文件夹名"})
    folder_path = StringField("Folder path", render_kw={"readonly": True, "hidden": True})
    create_btn = SubmitField("创建文件夹")

class UploadFileForm(FlaskForm):
    upload_file_name = MultipleFileField("File name")
    folder_path = StringField("Folder path", render_kw={"readonly": True, "hidden": True})
    upload_btn = SubmitField("上传所有文件")

localbin/core/__init__.py
"""
core is the main Blueprint for localbin responsible for rendering the UI and calling
:utils.module to load modules that are responsible for displaying specific user data
"""

localbin/core/routes.py
import json
import os
from pathlib import Path

from flask import Blueprint
from flask import render_template, flash, session, send_file
from flask_login import login_required
from werkzeug.security import safe_join

from localbin.core.forms import CreateFolderForm, UploadFileForm
from localbin.utils.convert_file_data import convert_file_stat
from localbin.utils.folder_navigation import get_user_location_path, get_user_upload_folder
from localbin.utils.folder_navigation import redirect_url_to_page_and_path

core = Blueprint('core', __name__, template_folder='../templates/core', static_folder='static')

@core.route("/", defaults={"requested_path": ""}, methods=["GET", "POST"])
@core.route("/<path:requested_path>")
@login_required
def index(requested_path):
    
    user = session['user']
    create_folder_form = CreateFolderForm()
    upload_file_form = UploadFileForm()
    
    user_folder = get_user_upload_folder() 
    abs_path = safe_join(user_folder, requested_path)
    
    if user not in abs_path:
        flash("Not allowed!")
        return redirect_url_to_page_and_path()
    
    if os.path.isfile(abs_path):
        try:
            return send_file(abs_path)
        
        except Exception as e:
            print(e)

    #all_files = [convert_file_stat(file, user_folder) for file in os.scandir(abs_path)]
    folders = [convert_file_stat(file, user_folder) for file in os.scandir(abs_path) if os.path.isdir(file.path)]
    files = [convert_file_stat(file, user_folder) for file in os.scandir(abs_path) if os.path.isfile(file.path)]

    parent_path = os.path.relpath(Path(abs_path).parents[0], user_folder)
    path_indicator = get_user_location_path(parent_path, requested_path)

    with open('localbin/translator/language.json', 'r', encoding='utf-8') as f:
        languages = json.load(f)

    return render_template("index.html", 
                           user_folder=user_folder, 
                           folders=folders,
                           files=files,
                           parent_path=parent_path, 
                           path_indicator=path_indicator,
                           create_folder_form=create_folder_form, 
                           upload_file_form=upload_file_form,
                           languages=languages,
                           os=os)

localbin/translator/routes.py
import os

from flask import Blueprint, request, redirect, flash
from flask_login import login_required
from werkzeug.security import safe_join
from werkzeug.utils import secure_filename

from localbin.translator import file_processing, tools
from localbin.utils.folder_navigation import get_user_upload_folder, redirect_url_to_page_and_path

translator = Blueprint('translator', __name__)


# 翻译函数
def translate(file_path, translated_folder_path, source_lang = 'osd', target_lang="中文"):
    # 获得文件链接
    file_type = file_processing.get_file_type(file_path)
    # 判断是否为支持翻译的文件类型
    if file_type in file_processing.supported_formats:
        # 判断是否为email
        if file_type in (".eml", ".msg"):
            # 调用邮件翻译功能，所有翻译后的文件均保存至processed文件夹
            translated_file_path = tools.QueryFileBase().translate_email(
                file_path,
                translated_folder_path,
                source_lang,
                target_lang
            )
        else:
            # 调用文件翻译功能，所有翻译后的文件均保存至processed文件夹
            translated_file_path = tools.QueryFileBase().translate_file_without_eml(
                file_path,
                translated_folder_path,
                source_lang,
                target_lang)

        return translated_file_path


@translator.route("/translate_file", methods=["POST"])
@login_required
# 文件翻译的接口
def translate_file():
    file_path = request.form.get('file_path')
    source_lang = request.form.get('source_lang')  # 获取源语言缩写
    user_folder = get_user_upload_folder()
    abs_path = safe_join(user_folder, file_path)
    # 获取文件的目录
    upload_directory = os.path.dirname(abs_path)

    # 定义子文件夹的路径
    translated_directory = os.path.join(upload_directory, 'translated')

    # 创建子文件夹（如果不存在的话）
    if not os.path.exists(translated_directory):
        os.makedirs(translated_directory)
    # 调用翻译函数，返回翻译后的文件路径
    translated_file_path = translate(
        file_path=abs_path,
        translated_folder_path=translated_directory,
        source_lang=source_lang
    )
    parent_path = os.path.dirname(file_path)
    flash("文件翻译成功！请点击右侧预览按钮或进入translated文件夹查看！")
    return redirect_url_to_page_and_path(parent_path)


@translator.route("/translate_folder", methods=["POST"])
@login_required
# 文件翻译的接口
def translate_folder():
    # 获取到文件夹相对路径
    folder_path = request.form.get("folder_path")
    source_lang = request.form.get('source_lang')  # 获取源语言缩写
    # 去掉前面的斜杠
    folder_path = folder_path.lstrip('/')
    # 获取到当前用户文件夹地址 例如：/Users/liangdake/localbin/localbin/users_space/liangke
    user_folder = get_user_upload_folder()
    # 获取到已上传文件夹地址
    abs_path_to_folder = os.path.join(user_folder, folder_path)
    # 定义子文件夹的路径
    translated_directory = os.path.join(abs_path_to_folder, 'translated')
    # 创建子文件夹（如果不存在的话）
    if not os.path.exists(translated_directory):
        os.makedirs(translated_directory)

    # 获得文件夹中所有文件，作为数组
    files = file_processing.get_files_with_absolute_paths(abs_path_to_folder)
    for file_path in files:
        # 获取文件名并构造翻译文件路径
        filename = os.path.basename(file_path)
        translated_file_path = os.path.join(translated_directory, filename.replace('.', '_Translated.'))

        # 跳过已翻译的文件
        if os.path.exists(translated_file_path):
            print(f"Skipping translation for {filename}: already translated.")
            continue
        try:
            # 进行翻译
            translated_file_path = translate(file_path=file_path, translated_folder_path=translated_directory, source_lang=source_lang)
        except (IOError, ValueError) as e:
            print(f"Translation error for {file_path}: {str(e)}")

    flash("当前文件夹所有文件翻译成功！请点击右侧预览按钮或进入translated文件夹查看！")
    return redirect_url_to_page_and_path(to_path=folder_path)

localbin/user/routes.py
import os
import shutil

from flask_login import login_required

from flask import request, flash, redirect, abort, session, url_for, render_template
from flask import send_file, jsonify
from werkzeug.security import safe_join
from werkzeug.utils import secure_filename

from localbin.translator import file_processing
from localbin.utils.compare_file import read_file_content, get_translated_file_path
from localbin.utils.folder_navigation import redirect_url_to_page_and_path
from localbin.utils.secure_files_and_folders import sanitize_folder_name, calculate_file_hash, allowed_file
from localbin.utils.folder_navigation import get_user_upload_folder
from flask import Blueprint

user = Blueprint('user', __name__, template_folder='templates', static_folder='static', static_url_path='/user/static')

@user.route("/return_to_root>", methods=["GET", "POST"])
@login_required
def return_to_root():
    """
    Route to return to root when clicking on folder icon next to the path indicator
    """
    return redirect_url_to_page_and_path()

# Route for create new folder
@user.route("/create_folder", methods=["GET", "POST"])
@login_required
def create_folder():
    """
    Route for creating new folder
    New folder name is sanitazed with custom function using re
    :sanitize_folder_name
    """  
    if request.method == "POST":
        new_folder_name = request.form.get("folder_name")
        current_path = request.form.get("folder_path")
        
        # Catch if any error occur
        try:
            sanitized_folder_name = sanitize_folder_name(new_folder_name)
        except Exception:
            flash("Name not supported! Try again!")
            return redirect_url_to_page_and_path(current_path)
        
        # Get user folder and current path level structure
        user_folder = get_user_upload_folder()
        folder_level = current_path[1:].split("/")

        # Construct the abs path
        abs_path_to_folder = safe_join(user_folder, *folder_level, sanitized_folder_name)
        
        # Check if new folder exists
        if os.path.exists(abs_path_to_folder):
            flash(f"与 '{sanitized_folder_name}' 同名文件夹已存在，请修改文件夹名称！")
            return redirect_url_to_page_and_path(current_path)
        
        # Create new folder or catch exception
        try:
            os.mkdir(abs_path_to_folder)
            flash(f"Folder {sanitized_folder_name} created!")
            return redirect_url_to_page_and_path(current_path)
        
        # Return error and redirect
        except Exception as error:
            flash("An error occured while creating folder! Please try again!")
            return redirect_url_to_page_and_path()
    
    return redirect_url_to_page_and_path()
     
# Route to download file
@user.route("/download/<path:requested_file>")
@login_required
def download(requested_file):
    
    user = session['user']
    user_folder = get_user_upload_folder()
    abs_path = safe_join(user_folder, requested_file)
    
    if user not in user_folder:
        return abort(404)
    
    # If the path doesnt exists abort
    if not os.path.exists(abs_path):
        flash("File doesnt exists! Redirecting to root!")
        return redirect_url_to_page_and_path()
 
    if os.path.isfile(abs_path):
        try:
            # Send the file to the client
            response = send_file(abs_path, as_attachment=True)

            # Calculate hash of the downloaded file
            file_hash = calculate_file_hash(abs_path)

            # Add file hash to response headers
            response.headers['X-File-Hash'] = file_hash

            return response
        
        except Exception as e:
            print(e)

# Verify file integrity after each request
@user.after_request
def verify_file(response):
    if request.endpoint == "download":
        # Get user path and file name
        user_folder = get_user_upload_folder()
        file_name = request.view_args["requested_file"]
        
        # Build path
        file_path = os.path.join(user_folder, file_name)
        
        # Calculate the original file hash and get the stored hash in the headers
        original_file_hash = calculate_file_hash(file_path)
        downloaded_file_hash = response.headers['X-File-Hash']
        
        # Compare original file hash with downloaded
        if original_file_hash != downloaded_file_hash:
            flash(f"Integrity error! Please try downloading the file: {file_name} again!")
        
        else:
            flash(f"{file_name} 已成功下载!")
        
        return response
    
    return response

# Route for upload file
@user.route("/upload_file", methods=["GET", "POST"])
@login_required
def upload_file():
    """
    This route handles file upload
    file name is secured with 
    :werkzeug.utils secure_filename()
    
    Allowed file extensions for now are 'txt, pdf, jpg, png, jpeg and gif'
    Max size is 15mb
    """
    if request.method == 'POST':
        user_folder = get_user_upload_folder()
        current_path = request.form.get("folder_path")
        
        folder_level = current_path[1:].split("/")

        # check if the post request has the file part
        if 'upload_file_name' not in request.files:
            flash('No file')
            return redirect_url_to_page_and_path()
        
        files = request.files.getlist('upload_file_name')
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        for file in files:
            if file.filename == '':
                flash('No selected file')
                return redirect(request.url)

            if file and allowed_file(file.filename):
                secured_filename = secure_filename(file.filename)
                # Construct the absolute path
                abs_path_for_upload = safe_join(user_folder, *folder_level)
                full_file_path = os.path.join(abs_path_for_upload, secured_filename)
                file.save(full_file_path)

                # Check if the file is a zip and handle accordingly
                if file.filename.endswith('.zip'):
                    try:
                        file_processing.unzip(full_file_path, abs_path_for_upload)
                        # 解压缩成功后删除原始 .zip 文件
                        os.remove(full_file_path)
                        flash(f"{file.filename} 已成功解压缩并上传，请检查文件是否遗漏！")
                    except Exception as e:
                        flash(f"解压缩 {file.filename} 失败: {str(e)}")

                else:
                    flash(f"{file.filename} 已成功上传！")

            else:
                flash(f"{file.filename}的文件格式不支持，请尝试更换文件后缀或重新上传!")

        return redirect_url_to_page_and_path(current_path)

    return redirect_url_to_page_and_path()

# Rename file or folder
@user.route("/rename_file", methods=["POST"])
@login_required
def rename():
    if request.method == "POST":
        old_file_name = request.json.get('old_file_name')
        file_name_suffix = request.json.get('file_suffix')
        new_file_name = request.json.get('new_file_name')
        path_to_file = request.json.get('path_to_file')
        
        # Construct the path
        user_folder = get_user_upload_folder()
        folder_level = path_to_file[1:].split("/")
        full_path_to_file = os.path.join(user_folder, *folder_level, old_file_name)
        
        # Secure file name and add the original extension
        secured_new_file_name = sanitize_folder_name(new_file_name)
        
        # Add suffix if file
        if os.path.isfile(full_path_to_file):    
            secured_new_file_name += f".{file_name_suffix}"
        
        # Construct the full path to the new file
        new_file_abs_path = safe_join(user_folder, *folder_level, secured_new_file_name)
        
        # Check if new file exists
        if os.path.exists(new_file_abs_path):
            flash(f"File with name '{secured_new_file_name}' already exists or name not allowed!")
            return jsonify({'error': 'Method not allowed'}), 400
        
        # Path to file to be renamed and the new path
        new_path_to_file = os.path.join(user_folder, *folder_level, new_file_abs_path)
        
        # Catch any error
        try:
            os.rename(full_path_to_file, new_path_to_file)
        except Exception as e:
            flash("Error while renaming!")
        
        # Return response
        return jsonify({'success': True, 'renamed_file': new_file_name}), 200
    else:
        return jsonify({'error': 'Method not allowed'}), 400

# Route for deleting file
@user.route("/delete_file", methods=["POST"])
@login_required
def delete_file():

    if request.method == "POST":
        user = session['user']
        file_to_delete = request.json.get('delete_file')
        path_to_file = request.json.get('path_to_delete_file')

        # Construct the path
        user_folder = get_user_upload_folder()
        folder_level = path_to_file[1:].split("/")
        full_path_to_file = os.path.join(user_folder, *folder_level, file_to_delete)

        if not user in full_path_to_file:
            flash("Not allowed!")
            return abort(404)

        if not os.path.exists(full_path_to_file):
            flash("Error deleting! No such file")
            return jsonify({'error': 'No such file!'}), 400

        try:
            if os.path.isfile(full_path_to_file):
                os.remove(full_path_to_file)

            elif os.path.isdir(full_path_to_file):

                shutil.rmtree(full_path_to_file)

        except Exception:
            flash("File cannot be deleted! Sorry")
            return jsonify({'error': 'Error!'}), 400

        return jsonify({'success': True}), 200

    return jsonify({'error': 'Method not allowed'}), 400


# 对比文件的路由
@user.route('/compare')
@login_required
def compare_files():
    # 原始文件路径
    file_path = request.args.get('file_link')
    lang = request.args.get('lang')
    user_folder = get_user_upload_folder()

localbin/templates/core/compare.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Comparison</title>
    <style>
        .container {
            display: flex;
            justify-content: space-between;
            width: 100%;
            height: 100vh;
        }
        .file-section {
            width: 48%;
            border: 1px solid #ccc;
            padding: 10px;
            overflow-y: auto;
            word-wrap: break-word;
        }
        .email-comparison {
        display: flex;
        justify-content: space-between;
        overflow: auto; /* 允许溢出时出现滚动条 */
        }
        .original-email, .translated-email {
            width: 45%;  /* 调整两边的宽度 */
            padding: 10px;
            border: 1px solid #ccc;
            background-color: #f9f9f9;
            border-radius: 5px;
            overflow: auto;  /* 当内容溢出时显示滚动条 */
            max-height: 600px;
        }
        pre {
            white-space: pre-wrap;  /* 自动换行 */
            word-wrap: break-word;
            line-height: 1.6;  /* 调整行距 */
            font-family: "Courier New", Courier, monospace;  /* 使用等宽字体，便于阅读 */
            background-color: #fafafa;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="file-section">
            <h3>原始文件: {{ original_filename }}</h3>
            <pre>{{ original_content }}</pre>
        </div>
        <div class="file-section">
            <h3>已翻译文件: {{ translated_filename }}</h3>
            <pre>{{ translated_content }}</pre>
            <h4>注意⚠️：预览文件仅供参考，精确翻译请下载：{{ translated_filename }}</h4>
        </div>
    </div>
</body>
</html>

localbin/templates/core/files_tr.html
<tr>
    <td id="td_for_rename text_start_table_th">
      <span class="hide_display_name ">
        <a href="{{ url_for('core.index', requested_path=file.file_link) }}"
              class="index_files">
          {% if file.file_type == 'file' %}
            <i class="{{ file.file_icon }} file_icon"></i>
          {% elif file.file_type == 'folder' %}
            <i class="{{ file.file_icon }} folder_icon"></i>
          {% endif %}
        {{ file.name }}
        </a>
      </span>
      <input
        class="bg-light index_files new_file_name"
        type="text"
        id="new_file_name"
        value="{{file.name}}"
        readonly
        hidden>
      <input class="display_name" type="text" value="{{file.name}}" hidden readonly>
      <button type="submit" class="save_btn text-light px-2" value={{path_indicator}} hidden>Save</button>
      <button type="submit" class="cancel_btn text-light px-2" hidden>Cancel</button>
    </td>
    <td class="center_table_th_td">
        {% if file.file_type == 'file' %}
          <form action="{{ url_for('translator.translate_file') }}" method="POST">
            <input type="hidden" name="file_path" value="{{ file.file_link }}">
                        <!-- 源语言选择下拉框 -->
          <label for="source_lang">源语言:</label>
          <select name="source_lang" id="source_lang">
            <!-- 循环动态生成选项 -->
            <option value="osd">自动检测</option>
            {% for language in languages %}
              <option value="{{ language.Code }}">{{ language.Title }}</option>
            {% endfor %}
          </select>
            <button type="submit" class="bi bi-translate"></button>
          </form>
        {% elif file.file_type == 'folder' %}
            <a class="ms-2 right_arrow_icon" href="{{ url_for('core.index', requested_path=file.file_link) }}"><i class="bi bi-arrow-right-square-fill h4"></i></a>
        {% endif %}
    </td>

    <td class="center_table_th_td">{{ file.size }}</td>
    <td class="center_table_th_td">
                    {% if file.file_is_translated and file.file_type == 'file' %}
                        <span style="color: green;">已翻译</span>
                    {% elif file.file_type == 'folder' %}
                    {% else %}
                        <span style="color: red;">未翻译</span>
                    {% endif %}
    </td>
    <td class="center_table_th_td">
      {% if 'file' in file.file_icon %}
        <form action="{{ url_for('user.compare_files') }}" method="GET">
            <!-- 文件路径，隐藏输入 -->
            <input type="hidden" name="file_link" value="{{ file.file_link }}">

            <!-- 源语言选择下拉框 -->
            <select name="lang" id="lang">
                <!-- 自动检测选项 -->
                <option value="osd">自动检测</option>
                <!-- 循环动态生成语言选项 -->
                {% for language in languages %}
                  <option value="{{ language.Code }}">{{ language.Title }}</option>
                {% endfor %}
            </select>

            <!-- 提交按钮（图标按钮） -->
            <button type="submit" class="bi bi-eye h5"></button>
        </form>
      {% endif %}
    </td>
    <td class="center_table_th_td">
      {% if 'file' in file.file_icon %}
        <a href="{{ url_for('user.download', requested_file=file.file_link) }}" class="ms-2 download_icon"><i class="bi bi-box-arrow-down h4"></i></a>
      {% endif %}
      <i class="bi bi-pencil-square h4 edit_file_name"></i>
      <i  class="bi bi-x-square-fill h4 delete_file delete_btn" value={{path_indicator}}></i>
    </td>
  </tr>

localbin/templates/core/index.html
{% extends "layout.html" %}

{% block title %}
    File Browser
{% endblock title %}

{% block body %}

  <section class="bg-light vh-100 vw-100">

    <div class="container mt-3 d-flex mb-1 create_folder_container">

        <div class="mt-5 me-2">
          <!-- Form for creating new folder -->
          <form action="{{ url_for('user.create_folder') }}", method="POST">
            {{ create_folder_form.csrf_token }}
            {{ create_folder_form.folder_name.label(class="hide-labels", for="folder_name")}}
            {{ create_folder_form.folder_name(class="form-control form-control-md") }}
            {{ create_folder_form.folder_path(class="", value=path_indicator) }}
            {{ create_folder_form.create_btn(class_="btn btn-sm w-100 mt-1 primary_buttons") }}
          </form>
        </div>

        <div class="input-group mb-2 mt-5 text-center">
          <div class="input-group ">
            <span class="input-group-text ms-2" id="basic-addon1">
              <a href="{{ url_for('user.return_to_root') }}"><i class="bi bi-folder2 text-primary"></i></a>
            </span>
            <input type="text"
             class="form-control form-control-md bg-secondary text-light"
              aria-label="current_working_directory"
              aria-describedby="working_directory"
              value="{{ path_indicator }}"
              name="path_indicator"
              readonly>
          </div>
          <div class="form-outline w-100 mt-1">
            <form action="{{ url_for('user.upload_file') }}" method="POST" enctype=multipart/form-data>
              {{ upload_file_form.csrf_token }}
              {{ upload_file_form.upload_file_name.label(class="hide-labels", for="upload_file_name") }}
              <div class="d-flex">
                {{ upload_file_form.folder_path(class="", value=path_indicator) }}
                {{ upload_file_form.upload_file_name(class="form-control mx-2 form-control-md w-100", id="upload_file_name") }}
                {{ upload_file_form.upload_btn(class_="btn primary_buttons btn-sm") }}
              </div>
            </form>
          </div>

          <form action="{{ url_for('translator.translate_folder') }}" method="POST">
            <input type="hidden" name="folder_path" value="{{ path_indicator }}">
                                    <!-- 源语言选择下拉框 -->
            <label for="source_lang">源语言:</label>
            <select name="source_lang" id="source_lang">
              <!-- 循环动态生成选项 -->
              <option value="osd">自动检测</option>
              {% for language in languages %}
                <option value="{{ language.Code }}">{{ language.Title }}</option>
              {% endfor %}
            </select>
            <button type="submit">翻译当前文件夹所有文件</button>
          </form>

        </div>
            </div>
      
    <div class="container bg-light">
          <table style="width: 100%;" class="ms-4 me-4">
            <thead>
              <tr class="">
                <th class="text_start_table_th">文件夹目录</th>
                <th class="center_table_th_td">进入文件夹</th>
                <th class="center_table_th_td">文件夹大小</th>
                <th class="center_table_th_td"></th>
                <th class="center_table_th_td"></th>
                <th class="center_table_th_td">文件夹操作</th>
              </tr>
            </thead>
            <tbody>
              {% if not parent_path == '..' %}
              <tr class="text-center">
                <td class="text_start_table_th">
                  <a href="">
                    <a href="{{ url_for('core.index', requested_path=parent_path) }}" class="return_arrow" class="text-primary"><i class="bi bi-arrow-90deg-left"> ..</i></a>
                  </a>
                </td>
              </tr>
              {% endif %}
              {% for file in folders %}
                  {% include 'files_tr.html' %}
              {% endfor %}
              
              {% for file in files %}
                {% if loop.index == 1 %}
                  <th class="text_start_table_th">文件列表</th>
                  <th class="center_table_th_td">翻译文件</th>
                  <th class="center_table_th_td">文件大小</th>
                  <th class="center_table_th_td">是否翻译</th>
                  <th class="center_table_th_td">预览文件</th>
                  <th class="center_table_th_td">文件操作</th>
                {% endif %}
                  {% include 'files_tr.html' %}
              {% endfor %}
            </tbody>
          </table>
    </div>
  </section>



  <script src="{{ url_for('static', filename='js/rename_and_delete.js') }}" defer></script>
{% endblock %}

localbin/templates/core/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>中科网航大模型翻译平台</title>

    
    <!-- Bootstrap 5 CDN's-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" defer>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- CSS link -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">

</head>
<body class="bg-light">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2 navbar1">
        <ul class="navbar-nav mr-auto">
            {% if current_user.is_authenticated %}
               <li class="nav-item active">
                   <a class="nav-link" href="{{ url_for('core.index') }}">主页</a>
               </li>
            {% endif %}
           </ul>
      </div>
      <div class="mx-auto order-0">
          <a class="navbar-brand mx-auto" id="brand-logo" href="#">中科网航大模型翻译平台</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar1">
              <span class="navbar-toggler-icon"></span>
          </button>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2 .navbar1">
          <ul class="navbar-nav ms-auto mx-3">
         {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">文档</a>
            </li>
          <li class="nav-item">
              <a class="nav-link " href="{{ url_for('auth.logout') }}">退出</a>
          </li>
        {% else %}
          <li>
            <a class="nav-link" href="{{ url_for('auth.login') }}">登陆</a>
          </li>
            <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
          </li>
        {% endif %}
          </ul>
      </div>
  </nav>

      {% if get_flashed_messages() %}
          <header>
              <div class="alert alert-primary mb-0 text-center" role="alert" style="background-color: yellow">
                  {{ get_flashed_messages() | join(" ") }}
              </div>
          </header>
      {% endif %}

      <section class="d-flex flex-column overflow-scroll mb-5">
        {% block body %}
        {%endblock body %}
      </section>
    <!-- Script link -->

    <!-- JavaScript link  <script src="{{ url_for('static', filename='file_browser.js') }}" defer></script> -->
    
    
    <!-- Script CDN for BootStrap 5 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>

</body>
</html>